apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: testing
  namespace: siliconchalet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: siliconchalet-app
    sources:
      stages:
      - development
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: ${REPOSITORY_URL}
          checkout:
          - branch: main
            path: ./repo
      - uses: helm-update-image
        as: update-image
        config:
          path: ./repo/values-testing.yaml
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.tag
            value: Tag
      - uses: git-commit
        as: commit
        config:
          path: ./repo
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: siliconchalet-app-testing
            sources:
            - repoURL: ${REPOSITORY_URL}
