apiVersion: apps/v1
kind: Deployment
metadata:
  name: siliconchalet-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: siliconchalet-app
  template:
    metadata:
      labels:
        app: siliconchalet-app
    spec:
      containers:
      - name: siliconchalet-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: html
        configMap:
          name: html-config
