apiVersion: v1
kind: Service
metadata:
  name: siliconchalet-app
  labels:
    app: siliconchalet-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: siliconchalet-app
