kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31443
        hostPort: 9000
      - containerPort: 31444
        hostPort: 9100
  - role: worker
  - role: worker
